# Generated by Django 5.0.3 on 2024-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cidades',
            new_name='Cidade',
        ),
        migrations.RenameModel(
            old_name='Editoras',
            new_name='Genero',
        ),
        migrations.DeleteModel(
            name='Autores',
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='leitor',
            options={'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leitor',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
